### ISSUE TITLE
can't load vqgan pretrianed weights

### ISSUE THREAD

**Issue by sicong-li** [ytongbai/LVM#20]
Hi I downloaded vaqgan's weights from [https://hf-mirror.com/amused/amused-256/tree/main/vqvae](https://hf-mirror.com/amused/amused-256/tree/main/vqvae)
However, due to the inconsistency of the network structure and some weight names, it cannot be loaded.
Can you reassign the VQGAN weights you used in your experiment？

**Comment by ytongbai** [comment]
We did, see README: https://github.com/ytongbai/LVM/blob/b6de939ef0eb1ee6593445a7f5268145f338749b/README.md?plain=1#L118

Thanks.

**Comment by sicong-li** [comment]
Thank you for your answer
I mistakenly clicked on the link to your project's homepage
